[package]
name = "rust-solana"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "box_type"
path = "src/box_type.rs"

[[bin]]
name = "deref_trait"
path = "src/deref_trait.rs"

[[bin]]
name = "rc_type"
path = "src/rc_type.rs"

[[bin]]
name = "refcell"
path = "src/refcell.rs"

[[bin]]
name = "trait_objects"
path = "src/trait_objects.rs"

[[bin]]
name = "pipeline"
path = "src/pipeline.rs"
